### PR TITLE
Implement System Integration on macOS #33

### PR DESCRIPTION
**Pull request by TitanNano**
1. I had to split the `site launch` command into two. The `site run` command now stays attached to the runtime process until the runtime is terminated, the `site launch` command should continue behaving as before.
2. The `site launch` command has to go through the system integration on macOS
3. I noticed that when launching a PWA with an empty profile (directory does not yet exist or is empty) the runtime launches with the Mozilla privacy notice instead of the PWA start URL. This seems not to be related to the macOS system integration though...

### CODE REVIEW

**Review by filips123 — CHANGES_REQUESTED** [review]
1. If I understand the code correctly:
   * The `site run` command just spawns the Firefox process, like `site launch` did before.
   * The `site launch` command on Windows and Linux still does this, but through some additional steps that eventually internally call `site run`. And on macOS, it runs installed `.app` bundle, which calls `site run`.

   Although this works, I think that it makes code a bit too complicated and harder to understand, as now it has to go through some additional functions and files. Could you instead of two commands for launching sites, add some macOS-only option/argument (maybe `--no-bundle` or `--direct-launch` or something similar) to the `site launch` command which determines whether it should call the `.app` or just spawn Firefox? So it would be something like this:

   * Windows and Linux: There is no additional argument. `site launch` just spawns Firefox directly as it did before this PR.
   * macOS: `site launch` (without any argument) first launches the `.app` file. This file then calls `site launch` again (but using the argument), which spawns Firefox.

2. See above...

3. This happens on all OSes, but because I was mostly testing PWAs with existing profiles, I kinda forgot about it. I will fix it later.

**Comment by filips123** [comment]
Clippy recently (with Rust 1.54.0) introduced some new rules, so checks will probably fail when you push a new commit. However, I've fixed them in https://github.com/filips123/FirefoxPWA/commit/981a00b4444d2783d47557bd7456d0849e68a503, so you will need to rebase your PR (and maybe also fix them in your additions).

I also implemented support for generating missing icons for PWAs and shortcuts from the first char of their names. I'm not sure how macOS application icons work, but you should probably add a check if the site does not have any icons, and generate an icon from the site name (with the required sizes) as I did for [Windows](https://github.com/filips123/FirefoxPWA/blob/981a00b4444d2783d47557bd7456d0849e68a503/native/src/integrations/windows.rs#L112-L116) and [Linux](https://github.com/filips123/FirefoxPWA/blob/981a00b4444d2783d47557bd7456d0849e68a503/native/src/integrations/linux.rs#L145-L148).

**Comment by TitanNano** [comment]
> Clippy recently (with Rust 1.54.0) introduced some new rules, so checks will probably fail when you push a new commit. > However, I've fixed them in 981a00b, so you will need to rebase your PR (and maybe also fix them in your additions).

Ok, thanks for letting me know. I will rebase.

> I also implemented support for generating missing icons for PWAs and shortcuts from the first char of their names. I'm not sure how macOS application icons work, but you should probably add a check if the site does not have any icons, and generate an icon from the site name (with the required sizes) as I did for Windows and Linux.

I will take a look at it and incorporate it into the macOS system integration.

**Review by filips123 — APPROVED** [review]
It looks fine, thanks! I pushed another commit that improves code quality a bit (fixes some typos, improves a few things, removes some unused functions, and reorganizes some code, including in my existing code), and adds additional non-W3C categories so all Apple categories are mapped (and I moved them to a separate file so the main macOS integration file isn't so big). Although it seems like a big commit, it shouldn't actually change functionality so much (hopefully).

I just have a few questions:

* It seems `site launch` `--url` argument got ignored when launching without `--direct-launch`. I added [`--args --url URL`](https://github.com/TitanNano/FirefoxPWA/blob/issues/33/native/src/integrations/macos.rs#L361-L362) to the `open` call which should pass "all remaining arguments to the opened application in the argv parameter to main()" ([source](https://ss64.com/osx/open.html)), and then accessed those arguments using [`"$@"`](https://github.com/TitanNano/FirefoxPWA/blob/issues/33/native/src/integrations/macos.rs#L265) in the loader and pass them back to `firefoxpwa`.

  Can you check if this works? Please try to open some PWA with a custom `--url` and check if it opens correctly.

* Are `xattr` and `codesign` always installed on macOS, or will I need to add as Homebrew dependencies or anything?

* Are there any other system integration-related things that work on Windows, macOS or in Chromium browsers, that you think would be useful, but are not implemented yet?

**Comment by TitanNano** [comment]
I added another commit to improve the icon handling. 
For some PWAs, it had trouble finding the best icon sizes. By filtering out all the unusable icons first, the size selection works much better.
It was also sometimes downloading icons which then were discarded because they couldn't be used, so I moved the request into a position where we are actually sure that we are going to use the icon.

>     * It seems `site launch` `--url` argument got ignored when launching without `--direct-launch`. I added [`--args --url URL`](https://github.com/TitanNano/FirefoxPWA/blob/issues/33/native/src/integrations/macos.rs#L361-L362) to the `open` call which should pass "all remaining arguments to the opened application in the argv parameter to main()" ([source](https://ss64.com/osx/open.html)), and then accessed those arguments using [`"$@"`](https://github.com/TitanNano/FirefoxPWA/blob/issues/33/native/src/integrations/macos.rs#L265) in the loader and pass them back to `firefoxpwa`.
>       Can you check if this works? Please try to open some PWA with a custom `--url` and check if it opens correctly.
I tried this with YouTube, and it appears to work. Launching the PWA from a channel page opens the page inside the PWA.

>     * Are `xattr` and `codesign` always installed on macOS, or will I need to add as Homebrew dependencies or anything?
Yes, these two come with the OS.

>     * Are there any other system integration-related things that work on Windows, macOS or in Chromium browsers, that you think would be useful, but are not implemented yet?
- I would like to apply the macOS 11 icon mask to the PWA icons, so they fit in with the other app icons. I have a WIP patch for it and will open an issue to explain this further.
- Perhaps we can get the share target API to work? I'm not sure yet, and have to look into how this works on macOS.
- On macOS, when closing all windows, an application is not being closed automatically. The app keeps running in the background and when the Dock icon is clicked, a new app window is being opened. At the moment, this new app window is opened with the Firefox home / new tab page, not the PWA start URL. I'd like to investigate and fix this, some time in the future.

**Comment by filips123** [comment]
Thanks! I think it should be fine for now and other things can be added in the future.

For share target and other similar APIs, I think we should probably wait a bit because most of them are still not standardized (share target is just unofficial draft, some other don't even have W3C page), so they can still be changed quite a lot or even dropped.

**Comment by filips123** [comment]
> On macOS, when closing all windows, an application is not being closed automatically. The app keeps running in the background and when the Dock icon is clicked, a new app window is being opened. At the moment, this new app window is opened with the Firefox home / new tab page, not the PWA start URL. I'd like to investigate and fix this, some time in the future.

I almost finished preparing the project for distribution in some package managers (including Homebrew), so I will soon release "stable" 1.0.0 version. Most features that I initially planned are implemented, and although there are still some problems, they are documented and will probably take quite a long time to fix.

If you have already started with fix for applications not being closed automatically and think you will finish it soon, I can wait for it before I release a new version. Otherwise, it's fine, I will just add it to the "current limitations" section and it can be fixed later.

**Comment by TitanNano** [comment]
> If you have already started with fix for applications not being closed automatically and think you will finish it soon, I can wait for it before I release a new version. Otherwise, it's fine, I will just add it to the "current limitations" section and it can be fixed later.

No I haven't done anything for this issue yet, I think you can go ahead. But to clarify, applications are not supposed to be automatically close on macOS. The issue rather is that when clicking on the app's dock icon it should open a new window of the application, so in our case the PWA and not the Firefox new tab page. I'll fill an issue, so we have this on record, and you can link to it.

**Pull request merged**
